### ISSUE TITLE
Unable to specify extended flag with Ecto type

### ISSUE THREAD

**Issue by Gr1N** [maennchen/crontab#64]
Hi,

Fix me please if I'm wrong, but as I see there is no way to specify `extended` with `Ecto.Type`. And according to the https://github.com/jshmrtn/crontab/blob/master/lib/crontab/cron_expression/ecto_type.ex#L47 expression always parses with `extended \\ false`. Is there any way to override that behavior?

Thanks.

**Comment by maennchen** [comment]
Hi @Gr1N 

You should be able to store an extended expression by storing a parsed expression and not a string of an expression.

**Comment by Gr1N** [comment]
Thank you for the response. But honestly, I don't think that your proposal is useful because when I use custom type and don't want to write additional casting logic because type already has it.

What do you think about adding an additional type? Something like `Ecto.ExtendedType`? Or maybe just update docs to do not have questions like mine?

**Comment by maennchen** [comment]
I don't really agree with your sentiment.

An extended cron expression (something I basically made up in this repository) is not distinguishable from a normal one since one is not required to write `*` for each unused field.

The cast for a string is only there for convenience, if you want full control, there's a Struct that specifies all possible use cases of an expression.

I agree though that this should probably be documented. Do you have a proposal on how to word that documentation notice?

Probably some examples should be provided as well.

**Comment by Gr1N** [comment]
I decided to fork Ecto type for my needs (maybe they are strange). But anyway thank you for the answer and I close the issue for now because don't know how to improve documentation in the right way.

**Comment by maennchen** [comment]
I think that it should be documented. Keeping it open therefore.

**Comment by maennchen** [comment]
Documentation resolved in 3120b84116f30566d7917f04b5a25ac3aad939ae
